export type ClockBox = { x: number; y: number; w: number; h: number };
export type ClockPlatform = ClockBox & { disappearing?: boolean; phase?: number };
export type ClockGear = { x: number; y: number; radius: number; speed: number; phase: number; dangerous: boolean };
export type ClockChain = { x: number; y: number; length: number };

export const CLOCK_TOWER_WORLD = { width: 1200, height: 4800 } as const;

/** A single, deliberately unforgiving climb. Every landing remains below the
 * player, so missing a jump costs height instead of dealing arbitrary damage. */
export const createClockTowerLevel = () => {
  const terrain: ClockBox[] = [
    { x: 0, y: 0, w: 46, h: CLOCK_TOWER_WORLD.height },
    { x: CLOCK_TOWER_WORLD.width - 46, y: 0, w: 46, h: CLOCK_TOWER_WORLD.height },
    { x: 0, y: CLOCK_TOWER_WORLD.height - 70, w: CLOCK_TOWER_WORLD.width, h: 70 },
    { x: 0, y: 0, w: CLOCK_TOWER_WORLD.width, h: 42 },
  ];
  const platforms: ClockPlatform[] = [];
  const gears: ClockGear[] = [];
  const chains: ClockChain[] = [];

  // Alternating narrow ledges form the main ascent. The vertical spacing is
  // within a double-jump, while the lateral rhythm keeps the route readable.
  for (let step = 0, y = 4620; y >= 170; step += 1, y -= 118) {
    const side = step % 4 < 2 ? 0 : 1;
    const width = step % 7 === 0 ? 112 : 138 + (step % 3) * 16;
    const x = side ? 1035 - width - (step % 2) * 105 : 65 + (step % 2) * 105;
    platforms.push({ x, y, w: width, h: 15, disappearing: step > 5 && step % 6 === 3, phase: step * .73 });

    // Periodic central transfer ledges stop the route becoming a simple wall jump.
    if (step % 5 === 2) platforms.push({ x: 500 + (step % 2) * 75, y: y - 54, w: 135, h: 14, disappearing: step % 10 === 7, phase: step * .41 });
  }

  // Both exits sit on permanent ledges at the highest reachable point.
  // Keep these references so door placement cannot drift away from the level geometry.
  const exitPlatforms: ClockPlatform[] = [
    { x: 210, y: 132, w: 238, h: 16 },
    { x: 752, y: 132, w: 238, h: 16 },
  ];
  platforms.push(...exitPlatforms);

  // Long chains visually stitch several storeys together.
  for (let i = 0; i < 10; i += 1) chains.push({ x: 225 + (i % 3) * 365, y: 120 + i * 430, length: 520 + (i % 2) * 240 });

  // Keep hazardous gears away from every landing and its jump approach. Gear
  // placement uses a separate fixed grid, so without this check it can overlap
  // a platform generated by the ascent pattern above.
  const gearPlatformClearance = 72;
  const isClearOfPlatforms = (gear: ClockGear) => platforms.every((platform) => {
    const closestX = Math.max(platform.x, Math.min(gear.x, platform.x + platform.w));
    const closestY = Math.max(platform.y, Math.min(gear.y, platform.y + platform.h));
    return Math.hypot(gear.x - closestX, gear.y - closestY) >= gear.radius + gearPlatformClearance;
  });
  for (let i = 0; i < 18; i += 1) {
    const gear: ClockGear = { x: 330 + (i % 3) * 270, y: 330 + i * 245, radius: 42 + (i % 3) * 10, speed: (i % 2 ? -1 : 1) * (.65 + (i % 4) * .13), phase: i * .91, dangerous: true };
    if (isClearOfPlatforms(gear)) gears.push(gear);
  }

  return { terrain, platforms, exitPlatforms, gears, chains };
};
